@endpoint = http://localhost:{{$dotenv PORT}}

# Home page #
GET {{ endpoint }}/

# User #

### Post SignUp
POST {{ endpoint }}/sign_up
Content-Type: application/json

{
    "nickname":"user3",
    "email":"user3@user.com",
    "password":"user3",
    "passwordConfirm": "user3"
}

### Post login
POST {{ endpoint }}/login
Content-type: application/json

{
    "email":"user@user.com",
    "password": "password"
}

### test autentificate token
GET {{endpoint}}/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyQHVzZXIuY29tIiwibmlja25hbWUiOiJ1c2VyIiwid2FsbGV0IjoiMTUwLjAwMDAiLCJpc0FkbWluIjpmYWxzZSwibWVkaWEiOm51bGwsImlhdCI6MTY2MTE1NTY1MSwiZXhwIjoxNjYxMTU1NjcxfQ.GaODGQxfUC0TVRtB9mA-CqLpHtU69E9NZKzHTFYw_6U

### refresh token
POST {{endpoint}}/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyQHVzZXIuY29tIiwibmlja25hbWUiOiJ1c2VyIiwid2FsbGV0IjoiMTUwLjAwMDAiLCJpc0FkbWluIjpmYWxzZSwibWVkaWEiOm51bGwsImlhdCI6MTY2MTE1NTY1MX0.Te3BFCsN3GxymMhCmYb1Y-c9KhWq3Hw9mBJHSnR6a-U"
}

### delete token
POST {{endpoint}}/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ1c2VyQHVzZXIuY29tIiwibmlja25hbWUiOiJ1c2VyIiwid2FsbGV0IjoiMTUwLjAwMDAiLCJpc0FkbWluIjpmYWxzZSwibWVkaWEiOm51bGwsImlhdCI6MTY2MDkxMzIyNH0.h0J1HmQnAeeKwl2mfyPcOzKNdaV5J8yFryjpYhkL2bY"
}